[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dask>=2025.3.0",
    "matplotlib>=3.5.3",
    "rasa-sdk>=3.6.2",
    "rasa<=3.6.21",
    "sqlalchemy<2.0",
    "packaging>=20.0,<21.0",
]
